version: "3"

networks:
  vpl:
    driver: bridge

# volumes:
#   database:CAMINHO_DO_HOST

services:
  # Example of container mysql.
  # vpl-bd:
  #   container_name: vpl-bd
  #   image: mysql
  #   env_file:
  #     - docker-variables.env
  #     * Create file docker-variables.env with these variables names:
  #     * MYSQL_USER=yourUser
  #     * MYSQL_PASSWORD=yourPassword
  #     * MYSQL_ROOT_PASSWORD=yourPassword
  #   ports:
  #     - 3306:3306
  #   networks:
  #     - vpl
  #   volumes:
  #     - ./data:/var/opt/mssql/data
  #   restart: always

  gateway-api:
    container_name: gateway-api
    image: luizracoelho/vpl-be-gateway-api:latest
    ports:
      - 8000:80
    networks:
      - vpl
    # volumes:
    #   - database:CAMINHO_CONTAINER
    restart: always

  price-list-api:
    container_name: price-list-api
    image: luizracoelho/vpl-be-price-list-service:latest
    ports:
      - 8001:80
    networks:
      - vpl
    environment:
      - SERVICES:VEHICLE=http://vehicles-api
      - DB:HOST=10.100.115.6
      - DB:PORT=33067
      - DB:USER=sa
      - DB:PASSWORD=Onsoft@2019#Apps
      - DB:DATABASE=dev-price-lists
    restart: always

  vehicles-api:
    container_name: vehicles-api
    image: luizracoelho/vpl-be-vehicles-service:latest
    ports:
      - 8002:80
    networks:
      - vpl
    environment:
      - SERVICES:PRICELIST=http://price-list-api
      - DB:HOST=10.100.115.6
      - DB:PORT=33067
      - DB:USER=sa
      - DB:PASSWORD=Onsoft@2019#Apps
      - DB:DATABASE=dev-vehicles
    restart: always

  auth-api:
    container_name: auth-api
    image: luizracoelho/vpl-be-auth-service:latest
    ports:
      - 8003:80
    environment:
      - DB:HOST=10.100.115.6
      - DB:PORT=33067
      - DB:USER=sa
      - DB:PASSWORD=Onsoft@2019#Apps
      - DB:DATABASE=dev-vehicles-auth
    networks:
      - vpl
    restart: always

  public-web:
    container_name: public-web
    image: luizracoelho/vpl-fe-public-web:latest
    ports:
      - 8020:80
    networks:
      - vpl
    restart: always

  admin-web:
    container_name: admin-web
    image: luizracoelho/vpl-fe-admin-web:latest
    ports:
      - 8021:80
    networks:
      - vpl
    restart: always